### ISSUE TITLE
Why bind the `data` directory the `/var/www/html`?

### ISSUE THREAD

**Issue by perfectra1n** [mother-of-all-self-hosting/ansible-role-nextcloud#5]
Currently, this creates a bind point for the `data` directory to the `/var/www/html` directory within the container
https://github.com/mother-of-all-self-hosting/ansible-role-nextcloud/blob/74845395e3b8ce2b2c8c0e641e0e4f288609df89/templates/systemd/server.service.j2#L30

Wouldn't we want to use the `nextcloud_base_path` instead? Shouldn't the `data` directory be mounted at `/var/www/html/data` point within the container?

Currently I have a folder for Nextcloud data on NFS. When I provided this role the `/mnt/nas` data directory in the variable `nextcloud_data_path`, the Nextcloud container wasn't able to run. However, when I set this line:
https://github.com/mother-of-all-self-hosting/ansible-role-nextcloud/blob/74845395e3b8ce2b2c8c0e641e0e4f288609df89/templates/systemd/server.service.j2#L30

To 
```
--mount type=bind,src={{ nextcloud_base_path }},dst=/var/www/html
```

It at least ran, but wasn't able to find any configuration files...

**Comment by spantaleev** [comment]
`nextcloud_base_path` is the base path of our Nextcloud installation, which includes various files that do not need to be passed to Nextcloud (`labels` for Traefik, `customized-container-src` when self-building is used, etc).

The `nextcloud_data_path` is the one where we store the actual data and the one we mount into the container at `/var/www/html`. You're probably confused because the `nextcloud_data_path` path (`/mash/nextcloud/data`) includes yet another `data` directory within it, among other files managed by Nextcloud (`console.php`, `cron.php`, etc).

What you have at `/mnt/nas` is probably that inner `data` directory and not the outer one.

I suppose you could do:

- `mkdir /mnt/nas/nextcloud-data`
- `mkdir /mnt/nas/nextcloud-data/data`
- `mv /mnt/nas/* /mnt/nas/nextcloud-data/data`
- `chown -R mash:mash /mnt/nas`
- now use `nextcloud_data_path: /mnt/nas/nextcloud-data` - this path includes a `data/` directory where the actual data is
