### ISSUE TITLE
`nextcloud_base_path` expansion

### ISSUE THREAD

**Issue by shukon** [mother-of-all-self-hosting/ansible-role-nextcloud#6]
Hi. I'm trying to install a second nextcloud instance within my mash-server, using a second playbook with a different `nextcloud_identifier`. However I'm wondering if I got the idea wrong, because the installation path of nextcloud is not being adapted.

[Here](https://github.com/mother-of-all-self-hosting/ansible-role-nextcloud/blob/4b1e795caf0c42da20060f7ce024a9aa7f5ddbd2/defaults/main.yml#L24C1-L24C59) it says
```
nextcloud_base_path: "{{ nextcloud_base_path }}/nextcloud"
```
where intuitively I'd expect
```
nextcloud_base_path: "{{ nextcloud_identifier }}/"
```

or maybe installing a second nextcloud actually needs a second mash-instance...?

**Comment by spantaleev** [comment]
The `nextcloud_base_path` definition seems incorrect - it should be something like `/{{ nextcloud_identifier }}`.

I'm practice, this is not a problem, because the playbook's `group_vars/mash_servers` file overrides it.

----

You cannot install 2 Nextcloud services on the same Ansible host. This is because the role is only included in the playbook once. It can't be included twice.

To install the same service twice (or more) to a given host, you can define the host twice (under a different name) and use a different playbook identifier (or base path) for the 2nd host.

**Comment by shukon** [comment]
> I'm practice, this is not a problem, because the playbook's group_vars/mash_servers file overrides it.

Makes sense.

> To install the same service twice (or more) to a given host, you can define the host twice (under a different name) and use a different playbook identifier (or base path) for the 2nd host.

Ok, so the identifier have to be different on playbook level, not just nextcloud level. I already have to playbooks, but I thought I might just use the same mash-everything and only change the nextcloud identifier + basepath.

Well, thanks anyway for the quick help :heart:
